// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://qpccxwtqidyzsrazlwvv.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InFwY2N4d3RxaWR5enNyYXpsd3Z2Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjQzODg2ODQsImV4cCI6MjA3OTk2NDY4NH0.4LxR2rhGSXbbRPZlqnHnl1F7UYbmjxdw_0d17qz-bB0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});